name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Docker build and push
        uses: cloudposse/github-action-docker-build-push@1.13.1
        with:
           context: ./src
           file: ./src/Dockerfile
           push: true
           #tags: |
           #  brokeoligarchy/live-kube-news:v1
           #  brokeoligarchy/live-kube-news:latest
